[package]
name = "crypto_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#pairing_ce = "0.28.5"
rabe-bn = "0.4.20"
rand = "0.8.5"